---
title: "Computational Musicology"
format: 
  dashboard:
    orientation: columns
    theme:
      - flatly
      - custom.scss
    toc: false
---

# Weekly Assignments {width=50%}

## Course Assignments

::: {.card}
### Week 7: Computational Musicology and (Audio) Visualisation
(not available right now, will be added later)
:::

::: {.card}
### Week 8: Chroma Features
(not available right now, will be added later)
:::

::: {.card}
### Week 9: Timbre Features / Self-Similarity Matrices
(not available right now, will be added later)
:::

::: {.card}
### Week 10: Key and Chord Estimation
(not available right now, will be added later)
:::

::: {.card}
### Week 11: Novelty Functions and Tempograms
Analysis of *Afraid to Feel* by LF System - [Open page](week11.html)
:::

::: {.card}
### Week 12: Classification and Clustering
Clustering my Spotify 2025 Wrapped -  [Open page](week12.html)
:::

# Portfolio {width=50%}

## Portfolio Overview

::: {.card}

### About me
My name is Stan Pieter van Kuik, and I am a 23-year-old Bèta-gamma student with a major in Artificial Intelligence. I live in Amsterdam and have a strong love for music, both as a listener and as a creator.

Besides studying, I enjoy producing my own music. Some of my the songs I made can be found on [Spotify](https://open.spotify.com/artist/0BBiXpXwpy9x3c0XsUWVRt) - the production quality is definitely not perfect, and most of them are quite old, but they still reflect an important personal side of my relationship with music. I hope you enjoy exploring this portfolio as much as I enjoyed making it.

### About This Portfolio
This portfolio explores whether my listening behavior differs between winter and summer. It is based on six playlists divided by both season and genre: chill, hip hop, and dance. The analyses move from a broad corpus exploration to more detailed feature analyses and finally to classification and reflection. You can find more information on the portfolio background if you press the link below. 

[Background page](portfolio/background.html)
:::

## Portfolio Sections

::: {.card}
### Corpus Exploration
A first general inspection of the corpus using Spotify track-level features.

[Open page](portfolio/corpus_exploration.html)
:::

::: {.card}
### Feature Analysis
Chroma, loudness, timbre, and temporal features.

[Open page](portfolio/feature_analysis.html)
:::

::: {.card}
### Classification and Clustering
A broader corpus-level analysis.

[Open page](portfolio/classification_clustering.html)
:::

::: {.card}
### Conclusion
What we have learned from this set of analyses and personal reflection.

[Open page](portfolio/conclusion.html)
:::